# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6579e02f9703a5242aa4f16c0ffa7dc05220fcc945e2c942379483818ecb74cd7ad1c2c7d2a403cbc7654d76e5afd4fc78daafdaf240df4987191b309521a4c3

test:
  secret_key_base: b17978b94a30fb8572e5de85651e8a9e884cf577d2e06a82946038658eca3992cde0b7711db7e38f73c9fcda5ba62fb6a1e353976bc62d57737151502f19cb7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
